language: julia
julia:
    - 1.0
os:
    - linux
notifications:
    email: false
addons:
# Set Python for PyPlot & gdal/netcdf for R/raster
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python  # python 2.7
    - PYTHON=python3 # python 3.5
before_install:
# Get R
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"
  - sudo apt-get update -qq -y
  - sudo apt-get install git r-base r-base-dev r-recommended -y
# Install raster (including dependencies such as rgdal & netcdf)
  - sudo apt-get install netcdf-bin libnetcdf-dev -y
  - sudo apt-get install libudunits2-dev -y
  - sudo apt-get install libgdal-dev libproj-dev -y
  - sudo R -q -e 'install.packages("raster", dependencies=TRUE, repos = "http://cran.us.r-project.org");'
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("MMpkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
- julia -e 'using Pkg; cd(Pkg.dir("MMpkg")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
